language: java
jdk:
- oraclejdk9
install: true
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- mvn install
- ./test.sh
after_success:
- "./publish-api.sh"
- "mvn sonar:sonar"
env:
  global:
    secure: FbQ2GOrg8FbAmjnvsBJVx8WGh0CxuCreCXiXjwSw+bsqn28nG62aMEh4YWnT5B0jLSAm4XRuQVVxePOjlMN07oiUVPTizA6Cej9ZhTwVpgiVlix2P1glFffLokjXXNGtd6/Bx8jivlfo+7eSNbBSjf+s5wf3KX5sYXdIAkgpC5iKMyKZgIoJ4jFqyBzJnh7l5/0u4Am3ULWm8K4I5ZpgZxrh5T3ws47FouJVcX39YJyqPPnqi9CI6MVLgCkUZW+OryOLMY+LiFu5h5BVBx0jcGyF1cBVnJQgNXE4qYSFhssfnyBqKMZp27gv9ncsNvx2w4/cTIQoI58mTdzDvThIfDM6H97KmYauSlYK/kpWdpBRfLiGw7px3yXr05chqk1unAVPPsrPfD2+y3lHVbdeGcwu9pUa8X8oBBTJ5pcR3ZuSgOQmzq6LfvJ0M8j8gZYNiG/TpSjgjXYB/ktBlYIjMZ7c7LGDuZHOJYHYzhSJKOP9I7v4nAEz35LbrWX2vOE7rf0LMpbMRzKhxlDZwUo8VNfbdXGn53OKUE/ABpBzmYJJjJxuGz2si0Fs0A7EI816eO+Ny52gwH2ahWDANDgn66cwWCzEzDQPQPz8yD5d2GylBnpsw7eyxWnB7edgwuNmvZ+oMu4E0ZbTGasBSTMN3m8zMMGCiWPGeDt6nGEbxMQ=
addons:
  sonarcloud:
    organization: ggam-github
    token:
      secure: "FKTPP9TVqShM9cGxucNZtUuvGlnEgSNF1uLamXRH42wnj3bIkTuibm+X0rZtdmBojUBtg69Dpv/J4brh8FARSbZ10BRH6WEXVQz351proUkt/UhtF3aecXORKmn+t/DJ9jrinpV2mdu/a4h3irhYXmAeHJihLq0JcZrP4o0PvVCPPEZMOKNs+aqFLcFL4NwoIelkFow6vpLeZY7znMpxFNEELdLf1dr44z82pTNhP6r6RDVbkWV/tlZ+GIkyvZ0zxdjM6gIbEdmxehri0ljwqtHntorf98PwaQx8IHod6hxF6FonkR9Ylf/rxVCa/q5KOZSrkNEg1+CwHxa65uXwU7wmSwxX+psryjz8EArFuSWy9vGil5YS6GHmaqGfWkP6Fj9q2m3fAZk20UTu4PAyeodRLEcpoDyMylwaybZCKcmctUSoapS6uHUM2YcBC3Bb/dm6SB9v3pxnidmp4bfabdiFz5YvQuLdFwhv2yzT4A8Q0n7YSy9d/Q3bkwB17ajm2emGJWNsHtTE+qYorxNfzKlTI8K5Rjf1KxvdM4G+lo2xehUH21z2fMpwfRKfLliuZCeu2HQW97FufeJjKoMi8d/6rEmkLz8EnOFs1iAClQTg8XUanIis2wdzsiHreW38Dh9K2/eaOpFQklZx+BGz0PfUCudXMLjp3QAzKaLrYSo="
