language: java
jdk:
- oraclejdk9
install: true
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- mvn install
- "./test.sh"
after_success:
- "./publish-api.sh"
- "mvn sonar:sonar"
env:
  global:
  - secure: FbQ2GOrg8FbAmjnvsBJVx8WGh0CxuCreCXiXjwSw+bsqn28nG62aMEh4YWnT5B0jLSAm4XRuQVVxePOjlMN07oiUVPTizA6Cej9ZhTwVpgiVlix2P1glFffLokjXXNGtd6/Bx8jivlfo+7eSNbBSjf+s5wf3KX5sYXdIAkgpC5iKMyKZgIoJ4jFqyBzJnh7l5/0u4Am3ULWm8K4I5ZpgZxrh5T3ws47FouJVcX39YJyqPPnqi9CI6MVLgCkUZW+OryOLMY+LiFu5h5BVBx0jcGyF1cBVnJQgNXE4qYSFhssfnyBqKMZp27gv9ncsNvx2w4/cTIQoI58mTdzDvThIfDM6H97KmYauSlYK/kpWdpBRfLiGw7px3yXr05chqk1unAVPPsrPfD2+y3lHVbdeGcwu9pUa8X8oBBTJ5pcR3ZuSgOQmzq6LfvJ0M8j8gZYNiG/TpSjgjXYB/ktBlYIjMZ7c7LGDuZHOJYHYzhSJKOP9I7v4nAEz35LbrWX2vOE7rf0LMpbMRzKhxlDZwUo8VNfbdXGn53OKUE/ABpBzmYJJjJxuGz2si0Fs0A7EI816eO+Ny52gwH2ahWDANDgn66cwWCzEzDQPQPz8yD5d2GylBnpsw7eyxWnB7edgwuNmvZ+oMu4E0ZbTGasBSTMN3m8zMMGCiWPGeDt6nGEbxMQ=
addons:
  sonarcloud:
    organization: "ggam-github"
    token:
      secure: Lv8vA6SkPOzMZXMNxPvSqPskV99lYQIZ+BNYzb3g2O/cOBtBWkOlUDUs/PpfSskZi2Jrtvgi3cW4M3rpCLqo+LYmEvfu83F7eXEHmLiX7vn2H8pKWrjB6LLt53sSwvy9rvT+WDOLaDrP8GlsQTTgthNld/7cS/hS52T1KGCpzZ+ACY6PUXR/awuseMx2tgqK2WuEuod1rH55AqWO3lGteTtCPdJgrUXUBvegfTd9q3KHfcc80CnQQJVscrEEWtFEnHLvAlNLQNEv6ywpb1QEJHR3Sl3hTxyUELcdWlIM3tsboncDxI/k6Hi/jOnnzeOe6+Hz7+ay3VSireiXPa+5BhTqbY/ykSO/wADkLQU8z6AxaT9BAfemmG2Zm3udzWaBx75ZyOi1+hXm2YGNKmlz0cKdOQI4uzrSFa8l1XN4TitkPcjvZSif21HUWPez3i+KkLV6CVeHRpAodhpZ40yjvws1oUzrzz8Pt3s/XMyqLQfup33woiqZLY6mZdAPETAgcApEGrASFXxoYCAEicqZ7c+KaDkSdHSrLS6ORpyGkNp06c1ou4aQOl6DseeHco4aC37Td/7uTpWPo1aDTte0Zo1+O8j+io82hFzjHHxotDSCIohyvT7hrYeC1idfGuXFnV5hNuluzD6Gqqxelp/gHdIyjFW1tHJTyFbldclB/mE=
