#!/bin/sh
BASEDIR="$(pwd $0)/$(dirname $0)/../"
cd $BASEDIR

java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6006 -Djava.util.logging.config.file=conf/logging.properties -p modules -m eu.ggam.container.Impl/eu.ggam.container.impl.Launcher $@