#!/bin/sh
DIR=`dirname $0`
BASEDIR=`pwd $0`
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6006 -Dserver.basedir=$BASEDIR/.. -p ../modules -m eu.ggam.container.Impl/eu.ggam.container.impl.Launcher $@